/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TidyUp;
import java.awt.Dimension;
import java.awt.Graphics;
import javax.swing.ImageIcon;

/**
 *
 * @author Nelson Portilla
 */
public class Fondo extends javax.swing.JPanel {

    /**
     * Creates new form Fondo
     */
    public Fondo() {
        initComponents();
        this.setSize(640, 347);
    }
    
    @Override
    public void paintComponent(Graphics g){
        //System.out.println("paintComponent");
        Dimension tamanio = getSize();        
        ImageIcon imagenFondo = new ImageIcon(getClass().
                getResource("/Icons/fondo2.jpg"));
        g.drawImage(imagenFondo.getImage(), 0, 0, 
                tamanio.width, tamanio.height, null);
        setOpaque(false);
        
        super.paintComponent(g);
    }    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btOrdenar = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 204));

        btOrdenar.setBackground(new java.awt.Color(255, 255, 255));
        btOrdenar.setForeground(new java.awt.Color(255, 255, 255));
        btOrdenar.setToolTipText("DO!");
        btOrdenar.setBorder(null);
        btOrdenar.setContentAreaFilled(false);
        btOrdenar.setFocusPainted(false);
        btOrdenar.setFocusable(false);
        btOrdenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btOrdenarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(184, 184, 184)
                .addComponent(btOrdenar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(182, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addComponent(btOrdenar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(111, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btOrdenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOrdenarActionPerformed
        //CREO LA LISTA DE NOMBRES DE ARCHIVOS//
        //        MakeList escribir = new MakeList();
        //
        //        GetNames leer = new GetNames();
        //        //Obtengo el vector con las canciones//
        //        Vector <String> lista = leer.leerArchivo("");
        //
        //        TidyUp tidyUp = new TidyUp();
        //        for(int i=0; i<lista.size()-1; i++){
            //            System.out.println("LISTA: "+lista.get(i));
            //            tidyUp.clasifyProcess(lista.get(i));
            //        }
        //
        //        InfoGui info = new InfoGui();
        //        info.setCount(lista.size()-1);
        //        info.setText(tidyUp.getprueba());
        //        info.setVisible(true);
    }//GEN-LAST:event_btOrdenarActionPerformed
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btOrdenar;
    // End of variables declaration//GEN-END:variables
}
